// Test generated by RoostGPT for test ReactUnitTesting using AI Type Open AI and AI Model gpt-4-1106-preview


import React from 'react';
import { render, screen } from '@testing-library/react';
import Projects from '../../src/pages/Projects';

// We start the test suite for the Projects component
describe('Projects component', () => {
  // Before each test, we render the Projects component anew
  beforeEach(() => {
    render(<Projects />);
  });

  // Test if Projects component renders correctly
  test('should render and display the Projects section', () => {
    const projectsSection = screen.getByRole('heading', { name: 'Projects' });
    expect(projectsSection).toBeInTheDocument();
  });

  // Test if the correct number of project cards are displayed
  test('should display the correct number of project cards', () => {
    const projectCards = screen.getAllByRole('article');
    expect(projectCards).toHaveLength(6); // Since the hardcoded list contains 6 items
  });

  // Test the first project card for correct data
  test('should display the correct first project information', () => {
    const firstProjectTitle = screen.getByText('Marketing site design & build');
    const firstProjectImage = screen.getAllByRole('img')[0];

    expect(firstProjectTitle).toBeInTheDocument();
    expect(firstProjectImage).toHaveAttribute('src', expect.stringContaining('project1.jpg'));
  });

  // ...additional tests for other project cards and edge cases
});

