// Test generated by RoostGPT for test ReactUnitTesting using AI Type Open AI and AI Model gpt-4-1106-preview


import React from 'react';
import { render, screen } from '@testing-library/react';
import Services from '../../../src/pages/Services';
import '@testing-library/jest-dom/extend-expect'; // For additional matchers

// Optionally mock framer-motion and images here if necessary
// jest.mock('framer-motion', () => ({
//   motion: {
//     div: ({ children }) => <div>{children}</div>
//   }
// }));
// jest.mock('../../../src/images/project1.jpg', () => 'test-project1-image');
// jest.mock('../../../src/images/project2.jpg', () => 'test-project2-image');

describe('Services component', () => {
  test('renders Services component', () => {
    render(<Services />);
    expect(screen.getByText('Services')).toBeInTheDocument();
  });

  test('renders correct number of services', () => {
    render(<Services />);
    const serviceCards = screen.getAllByRole('img'); // Assuming each Card has an img
    expect(serviceCards.length).toBe(3);
  });

  // More tests can be added for individual Card details, animations, etc.
});

