// Test generated by RoostGPT for test ReactUnitTesting using AI Type Open AI and AI Model gpt-4-1106-preview


// Import necessary dependencies and utilities
import React from 'react';
import { render, screen } from '@testing-library/react';
import { BrowserRouter as Router } from 'react-router-dom';
import '@testing-library/jest-dom/extend-expect';

// Relative path adjustment from tests directory to component directory
import Header from '../../../src/Components/Header';

// Mocking react-bootstrap and react-router-dom dependencies
jest.mock('react-bootstrap', () => ({
  Navbar: ({ children }) => <div>{children}</div>,
  Container: ({ children }) => <div>{children}</div>,
  Nav: ({ children }) => <nav>{children}</nav>,
}));

jest.mock('react-router-dom', () => ({
  Link: 'a',
  NavLink: 'a',
}));

describe('Header component tests', () => {
  test('renders the Header component with navigation links', () => {
    render(
      <Router>
        <Header />
      </Router>
    );

    // Expect the navigation links to be in the document
    const homeLink = screen.getByText('Home');
    const projectsLink = screen.getByText('Projects');
    const servicesLink = screen.getByText('Services');
    const aboutLink = screen.getByText('About');
    const contactLink = screen.getByText('Contact');

    expect(homeLink).toBeInTheDocument();
    expect(projectsLink).toBeInTheDocument();
    expect(servicesLink).toBeInTheDocument();
    expect(aboutLink).toBeInTheDocument();
    expect(contactLink).toBeInTheDocument();
  });

  // You can add more test cases here to test the active style
  // and other functionality as needed
});

