// Test generated by RoostGPT for test ReactUnitTesting using AI Type Open AI and AI Model gpt-4


import React from 'react';
import { render, cleanup } from '@testing-library/react';
import { useScroll, useSpring } from "framer-motion";
import About from './About';

jest.mock('framer-motion', () => ({
  useScroll: jest.fn(),
  useSpring: jest.fn(),
  motion: {
    div: ({ children }) => <div>{children}</div>,
  },
}));

afterEach(cleanup);

describe('About component', () => {
  beforeEach(() => {
    useScroll.mockReturnValue({ scrollYProgress: 1 });
    useSpring.mockReturnValue(1);
  });

  it('renders without crashing', () => {
    render(<About />);
  });

  it('renders correct content', () => {
    const { getByText } = render(<About />);
    expect(getByText('About')).toBeInTheDocument();
  });

  it('renders correct style', () => {
    const { getByText } = render(<About />);
    expect(getByText('About')).toHaveStyle(`scaleX: ${1}`);
  });
});
