// Test generated by RoostGPT for test ReactUnitTesting using AI Type Open AI and AI Model gpt-4


import React from 'react';
import { render, fireEvent } from '@testing-library/react';
import Contact from './Contact';

describe('Contact form', () => {
  let getByTestId;
  
  beforeEach(() => {
    ({ getByTestId } = render(<Contact />));
  });

  it('should validate form on submit', () => {
    const form = getByTestId('contact-form');
    const nameInput = getByTestId('name-input');
    const emailInput = getByTestId('email-input');
    const messageInput = getByTestId('message-input');
    const submitButton = getByTestId('submit-button');

    fireEvent.change(nameInput, { target: { value: 'Test Name' } });
    fireEvent.change(emailInput, { target: { value: 'test@test.com' } });
    fireEvent.change(messageInput, { target: { value: 'Test Message' } });
    fireEvent.click(submitButton);

    expect(form.checkValidity()).toBe(true);
  });

  it('should not validate form if any field is empty', () => {
    const form = getByTestId('contact-form');
    const nameInput = getByTestId('name-input');
    const emailInput = getByTestId('email-input');
    const messageInput = getByTestId('message-input');
    const submitButton = getByTestId('submit-button');

    fireEvent.change(nameInput, { target: { value: '' } });
    fireEvent.change(emailInput, { target: { value: 'test@test.com' } });
    fireEvent.change(messageInput, { target: { value: 'Test Message' } });
    fireEvent.click(submitButton);
    
    expect(form.checkValidity()).toBe(false);
  });
});
