// Test generated by RoostGPT for test ReactUnitTesting using AI Type Open AI and AI Model gpt-4


import React from "react";
import { render } from "@testing-library/react";
import { motion } from "framer-motion";
import Home from "./Home";

describe("Home component", () => {
  test("renders correctly", () => {
    const { asFragment } = render(<Home />);
    expect(asFragment()).toMatchSnapshot();
  });

  test("renders with name Dipesh Malvia", () => {
    const { getByText } = render(<Home />);
    const nameElement = getByText(/Dipesh Malvia/i);
    expect(nameElement).toBeInTheDocument();
  });

  test("renders with description FullStack Developer and Youtube Teacher based in Poland", () => {
    const { getByText } = render(<Home />);
    const descElement = getByText(/FullStack Developer and Youtube Teacher based in Poland/i);
    expect(descElement).toBeInTheDocument();
  });
});
