// Test generated by RoostGPT for test ReactUnitTesting using AI Type Open AI and AI Model gpt-4


import React from 'react';
import { render, screen } from '@testing-library/react';
import Projects from './Projects';

describe('Projects', () => {
  beforeEach(() => {
    render(<Projects />);
  });

  test('renders Projects component correctly', () => {
    const headingElement = screen.getByText(/Projects/i);
    expect(headingElement).toBeInTheDocument();
  });

  test('renders correct number of projects', () => {
    const cardElements = screen.getAllByRole('img');
    expect(cardElements.length).toBe(6);
  });

  test('renders unique project names', () => {
    const projectNames = ["Marketing site design & build", "Glide Utilities", "Noton High Street Product", "Gifts and Voucher Today", "Productkart Studio", "Library Management"];
    projectNames.forEach(name => {
      const nameElement = screen.getByText(new RegExp(name, 'i'));
      expect(nameElement).toBeInTheDocument();
    });
  });

  test('renders correct images for each project', () => {
    const imageElements = screen.getAllByRole('img');
    imageElements.forEach((imageElement, index) => {
      expect(imageElement).toHaveAttribute('src', index % 2 === 0 ? project1 : project2);
    });
  });
});
