// Test generated by RoostGPT for test ReactUnitTesting using AI Type Open AI and AI Model gpt-4


import React from 'react';
import { render, cleanup } from '@testing-library/react';
import { Services } from './Services';

describe("Services Component", () => {
  afterEach(cleanup);

  test("renders Services component", () => {
    const { getByText } = render(<Services />);
    expect(getByText('Services')).toBeInTheDocument();
  });

  test("renders correct number of service cards", () => {
    const { getAllByRole } = render(<Services />);
    const cards = getAllByRole('img');
    expect(cards.length).toBe(3);
  });

  test("renders correct service names", () => {
    const { getByText } = render(<Services />);
    expect(getByText('Consulting')).toBeInTheDocument();
    expect(getByText('Web Application Development')).toBeInTheDocument();
    expect(getByText('Products Support')).toBeInTheDocument();
  });
});
