// Test generated by RoostGPT for test ReactUnitTesting using AI Type Open AI and AI Model gpt-4-1106-preview


// __tests__/src/App.test.js

import React from 'react';
import { render, screen } from '@testing-library/react';
import '@testing-library/jest-dom';
import { MemoryRouter, Route, Routes } from 'react-router-dom';
import App from '../../src/App';

// Use jest.mock to mock any hooks or components that are imported and are not relevant for testing App directly
jest.mock('../../src/pages/About', () => () => <div>About Page</div>);
jest.mock('../../src/pages/Contact', () => () => <div>Contact Page</div>);
jest.mock('../../src/pages/Home', () => () => <div>Home Page</div>);
jest.mock('../../src/pages/Projects', () => () => <div>Projects Page</div>);
jest.mock('../../src/pages/Services', () => () => <div>Services Page</div>);
jest.mock('../../src/Components/Header', () => () => <header>Header Component</header>);

describe('App component', () => {
  test('renders App component with Header and Container', () => {
    render(
      <MemoryRouter>
        <App />
      </MemoryRouter>
    );

    expect(screen.getByRole('banner')).toHaveTextContent('Header Component');
    expect(screen.getByRole('main')).toBeInTheDocument();
  });

  test('routes to the correct page components', () => {
    const routes = [
      { path: '/', content: 'Home Page' },
      { path: '/projects', content: 'Projects Page' },
      { path: '/services', content: 'Services Page' },
      { path: '/About', content: 'About Page' },
      { path: '/contact', content: 'Contact Page' },
    ];

    routes.forEach(route => {
      render(
        <MemoryRouter initialEntries={[route.path]}>
          <Routes>
            <Route path="/" element={<App />} />
          </Routes>
        </MemoryRouter>
      );
      
      expect(screen.getByText(route.content)).toBeInTheDocument();
    });
  });
});

