// Test generated by RoostGPT for test ReactUnitTesting using AI Type Open AI and AI Model gpt-4


import React from "react";
import { render } from '@testing-library/react';
import { BrowserRouter as Router } from 'react-router-dom';
import Header from './Header';

describe('Header Component', () => {
  let component;

  beforeEach(() => {
    component = render(
      <Router>
        <Header />
      </Router>
    );
  });

  test('renders brand name', () => {
    const { getByText } = component;
    const brandElement = getByText(/Dipesh Malvia/i);
    expect(brandElement).toBeInTheDocument();
  });

  test('renders correct navigation links', () => {
    const { getByText } = component;
    const homeLinkElement = getByText(/Home/i);
    const projectsLinkElement = getByText(/Projects/i);
    const servicesLinkElement = getByText(/Services/i);
    const aboutLinkElement = getByText(/About/i);
    const contactLinkElement = getByText(/Contact/i);

    expect(homeLinkElement).toBeInTheDocument();
    expect(projectsLinkElement).toBeInTheDocument();
    expect(servicesLinkElement).toBeInTheDocument();
    expect(aboutLinkElement).toBeInTheDocument();
    expect(contactLinkElement).toBeInTheDocument();
  });
});
